### PR TITLE
Feature/ally2

### PR DESCRIPTION
**Pull request by yalania**
- Ally has now two forms, humanoid (only for intro) and lightball
- Added some triggers for ally behaviour, to force the player to tak with the ally and to force conversations on lightball mode

Need to add animations, visual effects and better texts. There is a bug if you go into the trigger starting the jump (animation get stuck) any suggestion?

### CODE REVIEW

**Review by Dartemiss — COMMENTED** [review]
GJ, works nice! I would put a cinematic at the beginning pointing to the ally, emphasising that you have to talk to him. Also, maybe on the dialogues or somehow it can tell you something about the mushdooms .
About when it becomes the lightball, it should explain that he will help you with some cool powers, and explains you how to use them (lightball and shield). Also, it should be implemented that the ally talks to you from your insides (just a dialog on ui, with his face).

**Review by JorxSS — CHANGES_REQUESTED** [review]
I found some problems with the Ally.
- Ally needs to have the GO Ally_positions in the scene and if not, crash. (And suggestion, change the GO name to Ally Positions without underscore)
- As we want to have level selection, we cannot use the lightball if we are in another level that isn't the first one.

**Comment by Dartemiss** [comment]
Second point that jordi commented is fixed on our branch of boss for being able of using it.
- "As we want to have level selection, we cannot use the lightball if we are in another level that isn't the first one."

**Comment by yalania** [comment]
- On Ally controller if you chose Ally_is_lightball (this setting is saved with the scene) you can use the lightball

**Review by JorxSS — APPROVED** [review]
LGTM

**Review by Dartemiss — APPROVED** [review]
GJ Anabel! Just what we have commented making play of the vfx!

**Pull request merged**
