### PR TITLE
Break line for ComponentText

### PR DESCRIPTION
**Pull request by marcorod94**
Now we could use \\n to break lines on dialogue

Use it with the same branch on the LittleOrion Engine

### CODE REVIEW

**Comment by yalania** [comment]
There is a weird animation when there is a jump, I don't know if it is because of the dialogue manager o the component implementation, could you check it?

**Review by Dartemiss — COMMENTED** [review]
imagen

**Comment by Dartemiss** [comment]
imagen

Also here is cut!

**Comment by marcorod94** [comment]
The last image isnt loading for future texts we should add \n to break the line

**Comment by Dartemiss** [comment]
Talk with @imarcuello for checking how the UI text should be please :D

**Comment by Dartemiss** [comment]
imagen

Now this happens for some reason

**Comment by Dartemiss** [comment]
imagen

Here too, there is like a weird tab

**Review by yalania — APPROVED** [review]

**Comment by Dartemiss** [comment]
This is not used as the \n doesnt work propertly and UI team is working on that. I close it

**Pull request closed without merging**
