### PR TITLE
Fix credits menu

### PR DESCRIPTION
**Pull request by luismoyano**
credits

Credits menu improved

### CODE REVIEW

**Comment by luismoyano** [comment]
Even thoug under Lead designer it says Mario's name, it's correct on the commit, I noticed the error while recording the gif

**Review by imarcuello — COMMENTED** [review]
On a second look I also saw that the title of credits it's a little bit deformed in the vertical axis. 
The rest with the gif modification it's ok.

**Comment by JorxSS** [comment]
@luismoyano I don't know if you currently fixed but, why "Producer" is not in caps? and also, why is not there our Lead Artist?

**Comment by luismoyano** [comment]
@JorxSS True, my mistake, its fixed now

**Review by vidalmelero — APPROVED** [review]

**Review by JorxSS — CHANGES_REQUESTED** [review]
image

**Review by imarcuello — APPROVED** [review]
I've seen the final outcome, with everything correcter it looks good!

**Review by JorxSS — APPROVED** [review]

**Pull request merged**
