### PR TITLE
Skip Cinematics

### PR DESCRIPTION
**Pull request by marcorod94**
This is the new skip cinematics for the new cinematics system currently working on the boss scene 

you could test it by loading the boss scene from the main scene

### CODE REVIEW

**Review by JordiRomagosa — APPROVED** [review]
Looks good to me

**Review by Dartemiss — CHANGES_REQUESTED** [review]
Works  fine excepts one thing. Sound. When you skip the cinematic, all boss sounds sound at the same time it is very weird. Also you can see how the boss is appears progressly instead of being there instantly.

**Comment by JordiRomagosa** [comment]
> 
> 
> Works fine excepts one thing. Sound. When you skip the cinematic, all boss sounds sound at the same time it is very weird. Also you can see how the boss is appears progressly instead of being there instantly.

Oh, yeah, sorry... I tested without audio.

**Comment by marcorod94** [comment]
The changes are done please review them

**Comment by Dartemiss** [comment]
It stills sounds the boss screaming (is intended?) and also if I have the controller connected instead of the J button, a controller button should appear

**Comment by marcorod94** [comment]
Fix the button error the total game pad wasn't been called, yes the sound is intended otherwise the scene will start with no music

**Comment by Dartemiss** [comment]
ALso, if cinematic is not skipped the indicator remains.

**Review by Dartemiss — APPROVED** [review]
LGTM

**Pull request merged**
